[metadata]
name = eeg_visualization_rqt
version = 0.0.1
author = tjalf
author_email = tjalf@example.com
home_page = https://github.com/TCUL8/-healthcare_msgs_demonstration
description = RQT plugin for visualizing raw and preprocessed EEG data side-by-side
license = Apache-2.0

[options]
zip_safe = True
include_package_data = True
packages = find:
python_requires = >=3.6
